### ISSUE TITLE
Cryptocurrencies, Blockchains, zkSnarks, zkStarks and the relevant literature

### ISSUE THREAD

**Issue by daviddias** [protocol/reading-group#7]
I've been working to catch up in all the literature with regards to CryptoCurrencies, Blockchains and so on. It happens that @dignifiedquire is also interested on getting up to speed on all the things and so we decided to create a reading/research group.

The goal of this groups is to:

- Review the CryptoCurrency, Blockchains and related literature
- Collect resources, notes and reviews so that this material becomes easier to digest by others in the org or future employees
- Develop the habit of reviewing papers as a org and ideally prepare presentations that can be used as a knowledge center (e.g of this in the wild is [`Papers we love`](http://paperswelove.org/)
- Become familiar with currenty implementations of Blockchains (i.e, geth, parity, zcash, etc) and hopefuylly contribute with documentation for those projects (we've spent countless hours trying to get our heads around geth and ethereumjs due to lack of documentation and out of date packages).

Everyone is welcome to join the study group, however, we do appreciate that everyone that signs up is commited to: a) attend sync ups and b) read the material. Think of this as a college course.

To formalize this and since the topic in study is broad, I propose that we name this group as `pl251`, meaning that is a Protocol Labs study group, advanced topic and on the Mathematical Foundations of Computing. This name follows the numbering system used by [Stanford](https://cs.stanford.edu/academics/courses)

With this name, we create a folder in this repo where we store references, material, notes, presentations and other artefacts generated.

**Comment by dignifiedquire** [comment]
Lets do it

**Comment by daviddias** [comment]
Starting the list of resources:

- [All the Bitcoin Research published so far](https://docs.google.com/spreadsheets/d/1VaWhbAj7hWNdiE73P-W-wrl5a0WNgzjofmZXe0Rh5sg/edit)
- [Coursera: Bitcoin and Cryptocurrency Technologies](https://www.coursera.org/learn/cryptocurrency) 
- [Stanford Online: Bitcoin and Crypto Currencies](http://online.stanford.edu/course/bitcoin-and-crypto-currencies) _currently not available, lectured by Dan Boneh_ we probably can ask for the materials.
- [Filecoin Paper and its references](https://filecoin.io/)

**Comment by dignifiedquire** [comment]
Where do we want to start? I think starting with the Filecoin Paper and the following along things that are not clear or referenced would be a good way to get going.

**Comment by daviddias** [comment]
I like that starting point. It will help us create better materials to help others understand Filecoin too. @nicola, is there a place where you are accumulating all the questions? the filecoin-faq?

Also, doing the Coursera course (that started last week) might be a good way to get a lot of breath of knowledge from already curated materials. They also have exercises that might be fun for the hacking together.

**Comment by dignifiedquire** [comment]
Subscribed to the Coursera course ✅

**Comment by tomatopeel** [comment]
There are these "awesome" lists also:

https://github.com/xasos/awesome-decentralized-papers
https://github.com/cmahon/awesome-cryptocurrency
https://github.com/sobolevn/awesome-cryptography

**Comment by miyazono** [comment]
Nicola has been putting Filecoin related questions as issues in [protocol/filecoin-research](https://github.com/protocol/filecoin-research)

Amusingly, Stanford already had an amusingly relevant [CS251: Cryptocurrencies, blockchains, and smart contracts](https://crypto.stanford.edu/cs251/syllabus.html) which included a [lab component](http://bitcoin.stanford.edu/)

When first bringing me onboard to help with the Filecoin whitepaper, Juan gave me these papers in this order:

[Bitcoin paper](https://bitcoin.org/bitcoin.pdf)
[Ethereum Mauve Paper](https://cdn.hackaday.io/files/10879465447136/Mauve%20Paper%20Vitalik.pdf)
[Ethereum Yellow paper](https://bravenewcoin.com/assets/Whitepapers/Ethereum-A-Secure-Decentralised-Generalised-Transaction-Ledger-Yellow-Paper.pdf)
[Filecoin paper](https://filecoin.io/filecoin.pdf)
[Zerocash extended paper](http://zerocash-project.org/media/pdf/zerocash-extended-20140518.pdf)
[Storj paper](https://storj.io/storj.pdf)
[Erasure Coding for Cloud Storage](http://static.usenix.org/events/fast/tech/full_papers/Khan.pdf)
[Permacoin](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/permacoin.pdf)
[Into the Ether with Ethereum Classic](https://ethereumclassic.github.io/assets/etc-thesis.pdf)
[SpaceMint: A Cryptocurrency Based on Proofs of Space](https://eprint.iacr.org/2015/528.pdf)
[Compact Proofs of Retrievability](https://cseweb.ucsd.edu/~hovav/dist/verstore.pdf)
[Randomized Byzantine Generals](http://ieeexplore.ieee.org/document/4568104/)
[Cryptocurrencies without Proof of Work](https://arxiv.org/pdf/1406.5694.pdf)

xasos's reading list looks great though, and cmahon linked to a [cryptography book](https://crypto.stanford.edu/~dabo/cryptobook/) DaBo is writing

**Comment by daviddias** [comment]
//cc @mishmosh
